### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by lguerard** [gkoulouras/easyFRAP-web#1]
Hi guys,

We just noticed that the website is off. We've been using it quite a lot when people wanted to analyze FRAP data.

Is that intentional or just a server issue ? 

If you don't support it anymore, do you have any pointers into what we could use instead ? 

Thanks a lot !

**Comment by gkoulouras** [comment]
Hi Iguerard,

Can't you access https://easyfrap.vmnet.upatras.gr/? It works fine on my end. Perhaps you experienced a temporary server downtime? Can you please confirm?

Thanks,
Greg

**Comment by lguerard** [comment]
Hi !

No, we're getting this error message when trying to access the site.

![image](https://github.com/gkoulouras/easyFRAP-web/assets/6182107/ffd038ea-b754-4bbd-bc3e-dfc0b76b6e0f)

Every other page works well though. No idea why it would be only this one :s

**Comment by gkoulouras** [comment]
That's odd. Are you behind any proxy that potentially prevents the website from being loaded? Have you tried from a different browser/network/device? I'm able to access the tool from either my laptop(s), tablet and my mobile phone (different network providers).

**Comment by lguerard** [comment]
I tried 2 different networks and 3 different devices and can't access it at all :s

**Comment by CGA-lab** [comment]
Hello!
I am in Portugal and also cannot access it. Get the error page not found. Is there another way around this?

**Comment by gkoulouras** [comment]
Hi All,

We have been notified by many users that the tool is not accessible in their countries. On the other hand, it does work for some other users which makes the investigation of the issue more complicated. We believe it's a DNS issue and we are working hard to resolve this in a timely manner. 

Please bear with us while we fix the issue. We will continue to update and support easyFRAP-web and provide it freely to the community. 

Thank you and apologies for any disruption.

Best regards,
Grigorios Koulouras

**Comment by gkoulouras** [comment]
Hi @lguerard and @CGA-lab,

It should work now. It was indeed a DNS issue, could you please confirm you can access the tool again?

Thanks again for your time to report this issue.

Best wishes,
Grigorios Koulouras

**Comment by CGA-lab** [comment]
Yes!

It works now!

Thanks a lot for the speedy response.

Are you thinking of a standalone version soon?

Another suggestion is most of the time. My movies have more than one spine
but only one background roi and the same field.
Right now, one can upload each uploaded .csv. Would it be possible to
submit more than one spine per uploaded spine?


I am enjoying a lot using your software.

Thanks

Claudia Almeida

Claudia Guimas Almeida, PhD

**Comment by gkoulouras** [comment]
Good to hear that!

There already exists a standalone version which is the predecessor of the web version.
here's the original paper: https://academic.oup.com/bioinformatics/article/28/13/1800/234733

But we strongly advice users to use easyFRAP-web instead, as this is the version we support and enhance over time. We have plans to update easyFRAP-web soon, so please use the "Feedback" form provided in the bottom-right corner of the website and kindly list any useful features you'd like to see in a future version.

Thanks again for being an active easyFRAP-er!

Best regards,
Grigorios Koulouras

PS. I'm now closing this ticket as the DNS issue is considered resolved. For any questions/suggestions you can always email us at **easyfrap {at symbol} upatras {dot symbol} gr**
